# Generated by Django 3.1.12 on 2023-03-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FinanceApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
